name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    env:
      # https://github.com/alx696/polong-core/releases
      POLONG_CORE_VERSION: v1.0.0

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare SSH and Get File
        env:
          # ED25519 Private Key
          SCP_PK: ${{ secrets.SCP_PK }}
          SCP_PATH_JKS: ${{ secrets.SCP_PATH_JKS }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SCP_PK" | tee $HOME/.ssh/id_ed25519
          chmod 400 $HOME/.ssh/id_ed25519
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null" | tee $HOME/.ssh/config
          scp $SCP_PATH_JKS app/lilu.red.jks
          rm $HOME/.ssh/id_ed25519
          sudo apt install -y wget
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_VERSION}/polong-core.aar -O gomobile/polong-core.aar

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        env:
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: 'app/build/outputs/apk/release/*.apk'
