name: CI

on:
  push:
    branches: [ main ]
#   release:
#     types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Prepare SSH
        env:
          # ED25519 Private Key
          SCP_PK: ${{ secrets.SCP_PK }}
          SCP_PATH_JKS: ${{ secrets.SCP_PATH_JKS }}
          SCP_PATH_AAR: ${{ secrets.SCP_PATH_AAR }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SCP_PK" | tee $HOME/.ssh/id_ed25519
          chmod 400 $HOME/.ssh/id_ed25519
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null" | tee $HOME/.ssh/config
          scp $SCP_PATH_JKS app/lilu.red.jks
          scp $SCP_PATH_AAR gomobile/

      - name: Build all artifacts
        env:
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

      - name: Publish
        env:
          SCP_PATH_APK: ${{ secrets.SCP_PATH_APK }}
        run: |
          ls app/build/outputs/apk/release
          scp app/build/outputs/apk/release/*.apk $SCP_PATH_APK
