name: CI

on:
  push:
    branches: [ main ]
#   release:
#     types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Prepare SSH
        env:
          # ED25519 Private Key
          SCP_PK: ${{ secrets.SCP_PK }}
          SCP_PATH_JKS: ${{ secrets.SCP_PATH_JKS }}
          SCP_PATH_AAR: ${{ secrets.SCP_PATH_AAR }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SCP_PK" | tee $HOME/.ssh/id_ed25519
          chmod 400 $HOME/.ssh/id_ed25519
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null" | tee $HOME/.ssh/config
          scp $SCP_PATH_JKS app/lilu.red.jks
          scp $SCP_PATH_AAR gomobile/

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        env:
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew build

      - name: Cleanup Gradle Cache
          # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
          # Restoring these files from a GitHub Actions cache might cause problems for future builds.
          run: |
            rm -f ~/.gradle/caches/modules-2/modules-2.lock
            rm -f ~/.gradle/caches/modules-2/gc.properties
        
      - name: Publish
        env:
          SCP_PATH_APK: ${{ secrets.SCP_PATH_APK }}
        run: |
          ls app/build/outputs/apk/release
          scp app/build/outputs/apk/release/*.apk $SCP_PATH_APK
