name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    env:
      # https://github.com/alx696/polong-core/releases
      POLONG_CORE_VERSION: v1.0.1

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare
        env:
          # ED25519 Private Key
          SSH_PK: ${{ secrets.ED25519_ALIYUN }}
          # jks path
          JKS_PATH: ${{ secrets.JKS_PATH }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_PK" | tee $HOME/.ssh/id_ed25519
          chmod 400 $HOME/.ssh/id_ed25519
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null" | tee $HOME/.ssh/config
          scp $JKS_PATH app/lilu.red.jks
          rm $HOME/.ssh/id_ed25519
          sudo apt install -y wget
          wget https://github.com/alx696/polong-core/releases/download/${POLONG_CORE_VERSION}/polong-core.aar -O gomobile/polong-core.aar

      - name: JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Package
        env:
          ANDROID_KEY_PASSWORD: ${{ secrets.JKS_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.JKS_PASSWORD }}
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          sudo apt-get install -y jq
          GIT_TAG=`echo $GITHUB_REF | sed 's/refs\/tags\///'`
          upload_url=`curl \
          -X POST \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
          -d '{"tag_name":"'${GIT_TAG}'"}'
          | jq --raw-output '.upload_url' \
          | sed 's/{?name,label}/?name/'`
          curl \
          -X POST \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          -F 'file=@app/build/outputs/apk/release/polong.apk' \
          ${upload_url}=android.apk
